import '/styles/globals.css'
import Nav from '../components/Nav'
import Providers from '@/providers/Providers'
import { Inter, Share_Tech_Mono } from 'next/font/google'
import { LayoutProvider } from './layoutProvider'

const inter = Inter({ subsets: ['latin'] })
const share_tech_mono = Share_Tech_Mono({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata = {
  title: 'Embedded Community | BSW TECH',
  description: 'Generated by create next app',
}

export default function RootLayout(
  { children }
    :
    { children: React.ReactNode }
) {
  return (
    <html lang="en" className="dark">
      <body >
        <main>
          <Providers>
            <LayoutProvider>
              {children}
            </LayoutProvider>
          </Providers>
        </main>
      </body>
    </html>
  )
}
