import React from 'react'
import '/styles/globals.css'
import Nav from '../components/Nav'

import { Inter, Share_Tech_Mono } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })
const share_tech_mono = Share_Tech_Mono({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata = {
  title: 'Embedded School | BSW TECH',
  description: 'Generated by create next app',
}

export default function RootLayout(
  { children }
    :
    { children: React.ReactNode }
) {
  return (
    <html lang="en">
      <body >
        <main>
          <div className={share_tech_mono.className}>
            <Nav />
          </div>
          {children}
        </main>
      </body>
    </html>
  )
}
